name: Automatic Release

on:
  push:
    branches: ["master"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set env variable
        run: |
          echo "NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV
      - name: List Files
        run: ls target/

      - name: Remove useless files
        run: rm target/original*

      - name: Rename File
        run: mv target/*.jar target/${{ env.NAME }}.jar

      - name: Automatic Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Builds"
          files: |
            target/*.jar